# Generated by `prpkgs export` on 2026-05-20T22:53:04. Do not edit by hand.
# Maps a leaf package name to the open nixpkgs PR snapshot that
# introduces it. Consumed by flake.nix.
{
  partydeck = {
    pr = 522351;
    rev = "095aece269d8a11bb3a0c628399e3e8f8f18839d";
    narHash = "sha256-Nv8CxKEk5OIBwnOdUz9/9vOkcNlaTrsNUoWLAsn69sI=";
    attr = "partydeck";
    version = "0.8.6";
    author = "colonelpanic8";
    mergeReady = false;
  };
  wacli = {
    pr = 496066;
    rev = "10b83564a225e7e409fe5aa3809cd1f96caafb48";
    narHash = "sha256-53iPlw2Jfuq6DQo/8GN/LQxVT+PXmGLvEOgiKsQHPDE=";
    attr = "wacli";
    version = "0.6.0";
    author = "macalinao";
    mergeReady = false;
  };
}
