# Generated by `prpkgs export` on 2026-05-22T08:11:35. Do not edit by hand.
# Maps a leaf package name to the open nixpkgs PR snapshot that
# introduces it. Consumed by flake.nix.
{
  Catask = {
    pr = 483167;
    rev = "28e075150e182feb3243ecc08221b02dbe326b50";
    narHash = "sha256-or8mKcPbBzX8bRLRd33xjoJpXPAPXI57PJkVV7CUJuA=";
    attr = "Catask";
    version = "2.7.0 and module";
    author = "LuNeder";
    mergeReady = false;
  };
  Fastflowlm = {
    pr = 513841;
    rev = "27d84bfe4923ae587d50399ec865422373fc09a7";
    narHash = "sha256-WiflYaJIszZ6bo5jDkG2/bTGQqPrSAxx9UHNT4wtWcw=";
    attr = "Fastflowlm";
    version = "";
    author = "JohnMolotov";
    mergeReady = false;
  };
  Squawker-vpn = {
    pr = 511846;
    rev = "1a337c2945fb9f89f5b31b4d2c4895e694f3aae8";
    narHash = "sha256-B6gbWpbLoXXJsgkjzb3JL1keBn7+oL3dP+JizXw6I7Q=";
    attr = "Squawker-vpn";
    version = "0.10.1";
    author = "mandar1jn";
    mergeReady = false;
  };
  account-utils = {
    pr = 453557;
    rev = "0764b60d06e9d6b0738b1444f1a464c2a5ee08b8";
    narHash = "sha256-Fff8hq8J1NlLTW3RdEqzYbUAfgrPiVdyPRHlU6z1PWY=";
    attr = "account-utils";
    version = "";
    author = "LordGrimmauld";
    mergeReady = false;
  };
  akeyless = {
    pr = 518105;
    rev = "3679c4038a97e3ae4534e7da1111279457e6c291";
    narHash = "sha256-50BHbcbnwUVkUhAAC7U6tV2AQF4hsqJ9Dl1ny3JFc+g=";
    attr = "akeyless";
    version = "1.143.0";
    author = "frantathefranta";
    mergeReady = false;
  };
  apache-hop = {
    pr = 397937;
    rev = "23b60a6fdb2ffe4eed7ebe767fc3d465c9a724ea";
    narHash = "sha256-iJnBt4Sk2BQUIw+7me8yj8ycS6kSV4YsBbwQ3RFVPW8=";
    attr = "apache-hop";
    version = "2.17.0";
    author = "das-g";
    mergeReady = false;
  };
  appium = {
    pr = 499472;
    rev = "296c69159dbc4b585508c150c6cb1a5386641526";
    narHash = "sha256-AEAd2VuJfBrTPjbXDcFPbkMyKAFIoXIs2i9u2yea3Pg=";
    attr = "appium";
    version = "3.3.0";
    author = "tom-xs";
    mergeReady = false;
  };
  aqualung = {
    pr = 410096;
    rev = "13bb3e179fbe811035e7ba428c1d99b7773aa745";
    narHash = "sha256-SJ72iWsJj3xR4XBgJDHTuGXGL+3/vpJDr4NX1ERPey4=";
    attr = "aqualung";
    version = "2.0";
    author = "amiryal";
    mergeReady = false;
  };
  armTrustedFirmwareJ784S4 = {
    pr = 323306;
    rev = "1ef0020f1486f734abbb6a47b553b65d53c23473";
    narHash = "sha256-30GBS5hbN+G+sP71Nnl41kvCMFhAu9Qmhm8WWe3S8Ro=";
    attr = "armTrustedFirmwareJ784S4";
    version = "2.10.0";
    author = "Titaniumtown";
    mergeReady = false;
  };
  artisan = {
    pr = 405028;
    rev = "3dc83a5d848286390f78531570c38bd7c04091a7";
    narHash = "sha256-pFkuxPaT57vik+7z2XLcX8R/ugKBGwO/cqkn+gG/nQo=";
    attr = "artisan";
    version = "";
    author = "Bohreromir";
    mergeReady = false;
  };
  asphalt = {
    pr = 506404;
    rev = "4aa662182950171f486dbde6666aa14a6c340595";
    narHash = "sha256-hV4k8BWOKV1SWXKnvk+FIdnEdEIRh8PWRRHImANVAOA=";
    attr = "asphalt";
    version = "2.0.0-rc.5";
    author = "mudmaster556";
    mergeReady = false;
  };
  auburn-sounds-renegate = {
    pr = 461475;
    rev = "341c32770859528784b2d8fc82472e4028997d90";
    narHash = "sha256-l448sIXU5jSAkADNAY6c0dUdFc1DzI0MKPqv5AN6S00=";
    attr = "auburn-sounds-renegate";
    version = "1.5.1";
    author = "mrtnvgr";
    mergeReady = false;
  };
  autopush-rs = {
    pr = 520214;
    rev = "129bbf2f8ed5cdf4c6d89afc34e042b85b94dc8f";
    narHash = "sha256-yUpjGgQrIXq7xYMU9AM8DjOMB4Q9twS2Q8WbLS5f4Tc=";
    attr = "autopush-rs";
    version = "1.81.3";
    author = "zimward";
    mergeReady = false;
  };
  aws-cloudformation-languageserver = {
    pr = 489310;
    rev = "2c319448bdf1b2caff6b5038b9fd9adf9bdd3e4a";
    narHash = "sha256-zX2kO96o0xZTEQYsEszMHo8ZdSz3OhTY2s6o7ASDhAg=";
    attr = "aws-cloudformation-languageserver";
    version = "1.4.0";
    author = "mbarneyjr";
    mergeReady = false;
  };
  azure-vpn-client = {
    pr = 511518;
    rev = "003c1091b4b3fedc6021a9d29311b3c9ad58976d";
    narHash = "sha256-0BbNCypWngidLMdIy0nvMz35CbeBR/f04B6viu3dkVk=";
    attr = "azure-vpn-client";
    version = "version 3.0.0 & NixOS module";
    author = "Elias-Graf";
    mergeReady = false;
  };
  bedrock-ops = {
    pr = 518492;
    rev = "264c0bc68df56c90128e349d5314119d4ae33ce2";
    narHash = "sha256-+tsGvNLvgagg+zRk54aGycASeAS2PFWOK71z5XVOj4o=";
    attr = "bedrock-ops";
    version = "0.1.0";
    author = "MukundaKatta";
    mergeReady = false;
  };
  bifrost = {
    pr = 521236;
    rev = "101373faf5f0eea995722046f276a205ade5099a";
    narHash = "sha256-8io4HN2MlcfJHN8W9iL/vH2BaBgwFVmLgSShd55IPjo=";
    attr = "bifrost";
    version = "1.5.3";
    author = "ManUtopiK";
    mergeReady = false;
  };
  brave-origin = {
    pr = 511131;
    rev = "2b8106a310a3ac7cb6bc97437d133c4042505e49";
    narHash = "sha256-ZPyWe7PyY21Vs8u9H6exjTQWc+ONqy9EpQUNLQdHhcg=";
    attr = "brave-origin";
    version = "1.91.157";
    author = "WitteShadovv";
    mergeReady = false;
  };
  buildPostgresql = {
    pr = 513940;
    rev = "38ee3fc18c913eb7e51e91cc875e2adf6f1309e8";
    narHash = "sha256-dAl+wXh8DuEaRSEQQsqtMJusPcs4frN7ZcIdw2CyqXY=";
    attr = "buildPostgresql";
    version = "";
    author = "wolfgangwalther";
    mergeReady = false;
  };
  cangaroo = {
    pr = 504791;
    rev = "46a0cb5d1f5992aaa680df6b47d3e3c90b6cd5c1";
    narHash = "sha256-x63mkmDDnCwkVkK+Vw3yRez4kASBnWsFyErZhLy63Ic=";
    attr = "cangaroo";
    version = "0.10.0";
    author = "SebastianWendel";
    mergeReady = false;
  };
  cataclysmDDA = {
    pr = 461699;
    rev = "109cf1642f651019441e843cd5840114c9bd6181";
    narHash = "sha256-bLIDvnU9O55G0o8K6RzJ8k+T2wH5AbyDHtQ7YmxwsWU=";
    attr = "cataclysmDDA";
    version = "";
    author = "RossSmyth";
    mergeReady = false;
  };
  ccsync = {
    pr = 456721;
    rev = "1be2fe74d67383cded09438ff03fcb8ac220033f";
    narHash = "sha256-R2y/se55Hzv6AgW+GQaywWP91XIrnJK+OCvUaMmjrq0=";
    attr = "ccsync";
    version = "0.1.5";
    author = "onsails";
    mergeReady = false;
  };
  charcoal = {
    pr = 493881;
    rev = "0e30db5bb478a17b9b16702c83e2bf6ff7761c17";
    narHash = "sha256-58nEigcdICQoWyUFP9BxSPdZdafCtnF0ZMK4dbWBjmM=";
    attr = "charcoal";
    version = "0.3.2";
    author = "Gorgeous-Patrick";
    mergeReady = false;
  };
  claude-code-webui = {
    pr = 461181;
    rev = "1f179a16bb7d9cbf28b0b84406214d07e9455520";
    narHash = "sha256-G9S+hQLV6PJZK/purSgn1pMsGt2fL7mA+iFB5BgwKVk=";
    attr = "claude-code-webui";
    version = "0.1.56";
    author = "luochen1990";
    mergeReady = false;
  };
  codex-auth = {
    pr = 517646;
    rev = "1740f2c84914cd1b824c39394928a2d5996c98b2";
    narHash = "sha256-eA4TDI3l88KAjtBk0WbOdjzXhBBl5VKuTMLWIBEAvkA=";
    attr = "codex-auth";
    version = "0.2.8";
    author = "Richienb";
    mergeReady = false;
  };
  comfyui = {
    pr = 515744;
    rev = "469943fbc3449f8378844c3de67604fdbafac2bb";
    narHash = "sha256-ouYWm0n0wMgriX9aKzueIsQFEhPlhueVvYNxGkYMPYc=";
    attr = "comfyui";
    version = "0.20.1 / 4.2.1";
    author = "caniko";
    mergeReady = false;
  };
  comfyui-manager = {
    pr = 515744;
    rev = "469943fbc3449f8378844c3de67604fdbafac2bb";
    narHash = "sha256-ouYWm0n0wMgriX9aKzueIsQFEhPlhueVvYNxGkYMPYc=";
    attr = "comfyui-manager";
    version = "0.20.1 / 4.2.1";
    author = "caniko";
    mergeReady = false;
  };
  commit-lsp = {
    pr = 457061;
    rev = "2441e26a3bd71c08a26f3a11c8ae2577f4d869a5";
    narHash = "sha256-xlLDS9oPhdIsPU6qKk2TTOVq27QSi0xMGKvtOemgw8g=";
    attr = "commit-lsp";
    version = "0.2.1";
    author = "kpbaks";
    mergeReady = false;
  };
  composia = {
    pr = 515061;
    rev = "103001823a38a8332ee97bd32b74fbb843845120";
    narHash = "sha256-z2jQzjyfadKoro2iRE2mMu/x5Y48ap/mE920GtcnIEo=";
    attr = "composia";
    version = "0.2.1";
    author = "alexma233";
    mergeReady = false;
  };
  container-canary = {
    pr = 444907;
    rev = "0e54d0837281bb199bb94c0e53a429744c24cf47";
    narHash = "sha256-en+BkScKuYhnsg1hDGRt2bYXdGHTTJ0YuR1K9kkcSLM=";
    attr = "container-canary";
    version = "0.5.0";
    author = "kpbaks";
    mergeReady = false;
  };
  copr-cli = {
    pr = 521630;
    rev = "0c70342974f24af771f083da1e03e0ebebf29a59";
    narHash = "sha256-q57ZiKRzV+BIaWJ8BXXzF6JHaoZa4U98RTGoBgF2Df4=";
    attr = "copr-cli";
    version = "2.5";
    author = "caniko";
    mergeReady = false;
  };
  core = {
    pr = 431137;
    rev = "0088a49394d70d045aa717ff7fb19b4436c3f63a";
    narHash = "sha256-BfTqPu54+cCX0Q83ymlKtOuR6lvG7LPS3Tkwl4r65Pw=";
    attr = "core";
    version = "0-unstable-2025-08-05";
    author = "yzhou216";
    mergeReady = false;
  };
  crash = {
    pr = 507180;
    rev = "2575c8bd783fe4ee2b045b396ced705b125ff25d";
    narHash = "sha256-GL3bpuGPkZYhs1ZDx3E49Z8YYd+xONMTHELyPgu9viQ=";
    attr = "crash";
    version = "9.0.1";
    author = "al3xtjames";
    mergeReady = false;
  };
  cstop = {
    pr = 463428;
    rev = "1e49b0678c4c4fa47c32708f666b0ddd99fbe254";
    narHash = "sha256-m+YaYrp3vFD9bpnK41/ERaBIbRu40ZXIWLZOOl0IEOI=";
    attr = "cstop";
    version = "1.0.1";
    author = "mrtnvgr";
    mergeReady = false;
  };
  cutadapt = {
    pr = 463556;
    rev = "2e34091d91ad6dcec2b2d0b0f1fc54337cbb8891";
    narHash = "sha256-6jwEJ2E5U/JCrB9+S7pWhDQwJWp/EhSlKQFqOls6wb8=";
    attr = "cutadapt";
    version = "5.2";
    author = "Kupac";
    mergeReady = false;
  };
  dealers-choice = {
    pr = 509887;
    rev = "12130a7603c52f7c6fb2e96343c9e772576e689a";
    narHash = "sha256-w1yiPjiVMe1m5y2wL+nhHa5AJywdayCsutRIA8c/lbI=";
    attr = "dealers-choice";
    version = "0.0.13";
    author = "andy5995";
    mergeReady = false;
  };
  deep-live-cam = {
    pr = 496013;
    rev = "395c5d024bce794fcaac82bf320a9a3d2e083316";
    narHash = "sha256-4dqzhNTyxxdqpJqzKEFzdRIbvEWSCHTe/i9+xgZVXYQ=";
    attr = "deep-live-cam";
    version = "2.6 and init dependencies";
    author = "S0AndS0";
    mergeReady = false;
  };
  defold = {
    pr = 459070;
    rev = "1d70bd99df9b33efe09b01e6a9ba232727550f59";
    narHash = "sha256-XHftnK2qqsqt6LTBBQ8g+cX5LWXhxkhIuEELWCckMi0=";
    attr = "defold";
    version = "1.12.4";
    author = "atomicptr";
    mergeReady = false;
  };
  delugia-code = {
    pr = 389348;
    rev = "226872e2a4f824acb008cddba12f907b41f92a22";
    narHash = "sha256-x3+Kh5n51P95hMqxogGHpdF4m1WOhESchcEvrKCuZzI=";
    attr = "delugia-code";
    version = "v2404.23";
    author = "evysgarden";
    mergeReady = false;
  };
  depot-tools = {
    pr = 515028;
    rev = "1fffaf33726f1d0dd60f0c53bb0d91550d1b9192";
    narHash = "sha256-caNfrww0VWGQI2LvSn0pp5VkiOqXAzVs5Ybm/u8QXpg=";
    attr = "depot-tools";
    version = "unstable-2026-04-29";
    author = "caniko";
    mergeReady = false;
  };
  difit = {
    pr = 481694;
    rev = "26fd89fe9afae6d7b669b4edc5f1788605e2028a";
    narHash = "sha256-JlEhUObHnzuGiy/Z/2BrZPLin+dYA3qpJqmw+T1SJRg=";
    attr = "difit";
    version = "3.1.10";
    author = "chansuke";
    mergeReady = false;
  };
  dockpin = {
    pr = 515481;
    rev = "4b54d531af0d2c24a3290e22d13c40e0eef02b6b";
    narHash = "sha256-7ej268HRa1/NjjyeuB8oKPb6OaSJ4Eg/qMYwhIGyk3A=";
    attr = "dockpin";
    version = "0.3.0";
    author = "kpbaks";
    mergeReady = false;
  };
  dotultimate = {
    pr = 348402;
    rev = "0817e06bb51d34d89ae62ef73520defad5c8ef70";
    narHash = "sha256-WPx9R7MyhkP6TCY8elI9NmyJraAkWJbst3fJ/2b/K1E=";
    attr = "dotultimate";
    version = "2025.2.4";
    author = "js6pak";
    mergeReady = false;
  };
  driftwm = {
    pr = 501860;
    rev = "2d8daa0c412d0487dc56455fc8032c388bdf4d81";
    narHash = "sha256-jNxhzoPnzjFgU786BUw9hrLKKRofpzg9klHaUrGj/Ws=";
    attr = "driftwm";
    version = "0.1.1";
    author = "yzhou216";
    mergeReady = false;
  };
  elegant-grub2-themes = {
    pr = 469429;
    rev = "1eabbd6aa42eabc3097544c2d162973b571c7226";
    narHash = "sha256-LH3EZnr3HSUa0p4nQYvLXj3op8B6wW6Xgh48/VAZkZk=";
    attr = "elegant-grub2-themes";
    version = "0-unstable-2025-09-13";
    author = "TutchMe";
    mergeReady = false;
  };
  envdiff = {
    pr = 481387;
    rev = "1f4e4e8bcf1b5350dd9868f02d711afbb7a0d3ab";
    narHash = "sha256-H5V0SQF9JMPoT/0SXovA1kssDSyf3F5enubftidyFYM=";
    attr = "envdiff";
    version = "0.2.0";
    author = "kpbaks";
    mergeReady = false;
  };
  epson-201202w = {
    pr = 159393;
    rev = "259f921a9b98881e5814330f4847fd7d134d771d";
    narHash = "sha256-UKvjybJrEzretpdJDa1JxnHWUjE0aUNi54eF8fFAMS8=";
    attr = "epson-201202w";
    version = "1.0.0";
    author = "palas";
    mergeReady = false;
  };
  evcxr-jupyter = {
    pr = 432632;
    rev = "3f8cd75e33c08ae8872a37e7517b7c3dd646ba9b";
    narHash = "sha256-N3005Ioecbthu4RFZIJrl+xcKO3e0MzDJIjrMN9VxsQ=";
    attr = "evcxr-jupyter";
    version = "0.21.1";
    author = "Guelakais";
    mergeReady = false;
  };
  fadein = {
    pr = 416572;
    rev = "49c229435183030f5ec030642d0e37fe74b4b33b";
    narHash = "sha256-1Nn/qSvWO3HssV0zq1XpeOUABQhmdYobFOiRQV0VV9E=";
    attr = "fadein";
    version = "5.0.11";
    author = "pancaek";
    mergeReady = false;
  };
  fastent = {
    pr = 521107;
    rev = "110ba1836eeb9429bd44115c795651eb8fa0fcf3";
    narHash = "sha256-BnQcYXFQyKZ+Nh6ExAqR6v8NsNdtNeYojSJRavahKNY=";
    attr = "fastent";
    version = "1.1";
    author = "mrbenjadmin";
    mergeReady = false;
  };
  firebird_5 = {
    pr = 513638;
    rev = "0d854f83daa65df75e8242a6d41bb9817b49e268";
    narHash = "sha256-cY/mi1/bMO9JW3a0IktpTICc8f2WpbL52HH3KCIS1ZM=";
    attr = "firebird_5";
    version = "5.0.4";
    author = "nixpkgs-ci[bot]";
    mergeReady = false;
  };
  fizzy = {
    pr = 511732;
    rev = "25f91c18c316963d62c3ec87bd8596b30d1accdc";
    narHash = "sha256-v2fSHkmt/z0KDCRiGUc5VUyTe7OtQ5EnaxAjuukg9ZY=";
    attr = "fizzy";
    version = "fizzy@bead275";
    author = "philocalyst";
    mergeReady = false;
  };
  flag-embedding = {
    pr = 440120;
    rev = "21ddee55481536021befcd7cf0566179600b13c3";
    narHash = "sha256-+ry+0hdOA/y950igpg3NaqHcnaY8XgXGPQ6lr+AqqAk=";
    attr = "flag-embedding";
    version = "";
    author = "Gurjaka";
    mergeReady = false;
  };
  flake8-builtins = {
    pr = 440120;
    rev = "21ddee55481536021befcd7cf0566179600b13c3";
    narHash = "sha256-+ry+0hdOA/y950igpg3NaqHcnaY8XgXGPQ6lr+AqqAk=";
    attr = "flake8-builtins";
    version = "";
    author = "Gurjaka";
    mergeReady = false;
  };
  flow5 = {
    pr = 504152;
    rev = "3b929e2577c77881c2a95f5bbec835673d09eecc";
    narHash = "sha256-724IdV0LdeDY3gAbmS1Sa6w0XuWYRXfSTeBbjRKR0oU=";
    attr = "flow5";
    version = "7.55";
    author = "jdelacroix";
    mergeReady = false;
  };
  flutter344 = {
    pr = 522824;
    rev = "415a1e1c95e42f9da6a657bf0df18a7fdd3083d0";
    narHash = "sha256-TZSvayy83miNnsCa3a/ro4kKNpFb0nZCvqqwifCzrqU=";
    attr = "flutter344";
    version = "3.44.0";
    author = "qzylinra";
    mergeReady = false;
  };
  fluxer-bin = {
    pr = 490554;
    rev = "25ca192deb78bb097551f7e5e0153830e496772c";
    narHash = "sha256-PJJiIHrKzC71lPPzUZpwRBcnuVOsODPsb58thm1Ygjw=";
    attr = "fluxer-bin";
    version = "0.0.8";
    author = "WoutFontaine";
    mergeReady = false;
  };
  fluxer-desktop = {
    pr = 497870;
    rev = "1ae22cc2ac826b381b1200fa445aa4d176db72f5";
    narHash = "sha256-rHjg/D5FUhZfKqnNPP2h9FqtdR5FpFwTWJr1RYqS6JE=";
    attr = "fluxer-desktop";
    version = "0.0.8-unstable-2026-04-09";
    author = "niklaskorz";
    mergeReady = false;
  };
  fnox = {
    pr = 511494;
    rev = "0cad835b0178a71d5e6020b50be14f6f2da02fa6";
    narHash = "sha256-ohVmbGH2j+6mk/wWhCQMbyTCG4s9ZaRYu6xTBAhWOKs=";
    attr = "fnox";
    version = "1.20.0";
    author = "tiptenbrink";
    mergeReady = false;
  };
  funkwhale = {
    pr = 512046;
    rev = "29a628b102b53dfd7bfa5ee606cbb4eae03155bc";
    narHash = "sha256-SyWXfJu1p8CLW+nugcxw1hmW1yVqJZ5xLiVR4RDa2d4=";
    attr = "funkwhale";
    version = "2.0.2";
    author = "phanirithvij";
    mergeReady = false;
  };
  ga68 = {
    pr = 507407;
    rev = "14619a225220839425ee2a91e7789a9a6d33be5a";
    narHash = "sha256-U95xeOdZDJhW3QKcpi9MLK1T2/TuzMt7M5kSlpu4R5U=";
    attr = "ga68";
    version = "";
    author = "sempiternal-aurora";
    mergeReady = false;
  };
  gavl = {
    pr = 518832;
    rev = "05f5cb5851a4aaded42e60c9dc4d8ac753a67e81";
    narHash = "sha256-bWHahh0KNQnWrs87A6mI5bNcZ/N6tGUcEgc7ibNhGHg=";
    attr = "gavl";
    version = "2.0.1";
    author = "tbutter";
    mergeReady = false;
  };
  gccrs = {
    pr = 507407;
    rev = "14619a225220839425ee2a91e7789a9a6d33be5a";
    narHash = "sha256-U95xeOdZDJhW3QKcpi9MLK1T2/TuzMt7M5kSlpu4R5U=";
    attr = "gccrs";
    version = "";
    author = "sempiternal-aurora";
    mergeReady = false;
  };
  gcobol = {
    pr = 507407;
    rev = "14619a225220839425ee2a91e7789a9a6d33be5a";
    narHash = "sha256-U95xeOdZDJhW3QKcpi9MLK1T2/TuzMt7M5kSlpu4R5U=";
    attr = "gcobol";
    version = "";
    author = "sempiternal-aurora";
    mergeReady = false;
  };
  gh-aw = {
    pr = 490246;
    rev = "2201c7b7c92fd2cbb33b5089b46145285b277136";
    narHash = "sha256-bGiH46fdqWo9wnjHuLjCEVaGmfrfl/Vnfd4mwTTwFQQ=";
    attr = "gh-aw";
    version = "0.68.3";
    author = "MH0386";
    mergeReady = false;
  };
  ghasec = {
    pr = 515502;
    rev = "0f197c6ad5acc89c1dce8e103acdbe254709619e";
    narHash = "sha256-UNGVvpnfnL8mmGnYexPwu+WHyez//Fd59c5nnU8t8VE=";
    attr = "ghasec";
    version = "0.11.2";
    author = "misogihagi";
    mergeReady = false;
  };
  git-native-issue = {
    pr = 521181;
    rev = "3747cb0b6db887f180291a6dec428e9a22f0bcb5";
    narHash = "sha256-q/ohTr7BiXK7jbg7WdhxHhwKf5pkw/v+QmVmzq4KaPY=";
    attr = "git-native-issue";
    version = "1.3.3";
    author = "kpbaks";
    mergeReady = false;
  };
  gitile = {
    pr = 391979;
    rev = "14f8dfc878338952175721d2f5b45831482b8f92";
    narHash = "sha256-6uX1donShtUroZID7FKlVIHgTGZKmeNvr1+iVJ4qnNE=";
    attr = "gitile";
    version = "0.4.0";
    author = "wahjava";
    mergeReady = false;
  };
  gnupg_25_experimental = {
    pr = 515601;
    rev = "10abf48cfee5102a76f3a2efe61471ac247cc2b2";
    narHash = "sha256-oz6buDuYi58KnJfBPF0IhErijNjwBWYP7IxpQQtgAeQ=";
    attr = "gnupg_25_experimental";
    version = "2.5.19";
    author = "dstremur";
    mergeReady = false;
  };
  go-webring = {
    pr = 448026;
    rev = "4ac79e0ba33343eac742dfc28d093464463f17e0";
    narHash = "sha256-zanTwKeQepEC5Ysbdz4xHgkpD+xVDesBv/s8okNYCiI=";
    attr = "go-webring";
    version = "";
    author = "kmein";
    mergeReady = false;
  };
  goal = {
    pr = 510789;
    rev = "4bbbb55ea39dfc639c5b5266dfaa3a7289e3adb4";
    narHash = "sha256-2O13cQ4yxSaDuPJ6XJb8lciD+8GzQNLQy+SMBSkuONc=";
    attr = "goal";
    version = "1.5.0";
    author = "slotThe";
    mergeReady = false;
  };
  gophie = {
    pr = 472348;
    rev = "3294b7dd6e4fd25d9e70b5ea4823ef4262ef0805";
    narHash = "sha256-4l4D7Xc96PTEhgp8g2E94YXwWJHwACU5UbOvIsM7cR8=";
    attr = "gophie";
    version = "1.1";
    author = "theobori";
    mergeReady = false;
  };
  gr-dect2 = {
    pr = 499864;
    rev = "43e809fdb15feddc60e5aea25c190ea6dc194fcf";
    narHash = "sha256-hQJhNCOpzROhbOSWWAYp3bzKrWfrpSfyiH396rQlmbo=";
    attr = "gr-dect2";
    version = "0-unstable-2025-03-16";
    author = "felbinger";
    mergeReady = false;
  };
  gram = {
    pr = 508631;
    rev = "1023d5dafaca347b9aafad9bc2bcfe51b4063813";
    narHash = "sha256-9oatxDmNVnGi+qY0LfcMbnuRMvstrell0sD8zqPNCWA=";
    attr = "gram";
    version = "2.1.0";
    author = "niklaskorz";
    mergeReady = false;
  };
  guac = {
    pr = 513459;
    rev = "3f6f667b378d6d3b431c5d9a00c24ce15d9ffa70";
    narHash = "sha256-44pA3ucXPZsUP/EPQlzZ2Fl1VXpgFg8U+2lAacbjhc8=";
    attr = "guac";
    version = "0.0.2";
    author = "kilisei";
    mergeReady = false;
  };
  handy = {
    pr = 507754;
    rev = "0712eb952b106a59525d24b830484afca1bfaf43";
    narHash = "sha256-S4dptDxNhcvq+wLyJGOgcPndsv33L4K53+LQen3Iir4=";
    attr = "handy";
    version = "0.8.3";
    author = "philocalyst";
    mergeReady = false;
  };
  helpwire-operator = {
    pr = 461899;
    rev = "14b3fd79f4208bfc2c7a0489ff4c22188e9fa28d";
    narHash = "sha256-Ic15AIU8g+dNKQSjCPV+18oynijKavIYsST5fbv7ju0=";
    attr = "helpwire-operator";
    version = "2.1.6.127";
    author = "filiptrplan";
    mergeReady = false;
  };
  himitsu-ssh = {
    pr = 276449;
    rev = "3b06ab8b2892034e706f1913097adf99adaeb03a";
    narHash = "sha256-fwV53I3DNA0OPWnPMVC64N4NT/q0rw60EeOwlUGEVHk=";
    attr = "himitsu-ssh";
    version = "unstable-2023-12-05";
    author = "patwid";
    mergeReady = false;
  };
  hister = {
    pr = 512162;
    rev = "3da516f5175714283dd76ea88814fb29743dfb39";
    narHash = "sha256-/vebNnTowYES+moToy7k+wFPirAiZA5xfzzvhQgA9G0=";
    attr = "hister";
    version = "0.13.0";
    author = "FlameFlag";
    mergeReady = false;
  };
  hk = {
    pr = 503171;
    rev = "29217fbe2f3d8bb5012f3c28e785cf80b4dbc374";
    narHash = "sha256-6X1pAT9ofuZLESZTdo8CdM40CIUkF33dutj6BIvDXfs=";
    attr = "hk";
    version = "1.45.0";
    author = "typedrat";
    mergeReady = false;
  };
  holesail = {
    pr = 432474;
    rev = "4558d071c02119d7eab1e8571f432e7a7cc2eb8d";
    narHash = "sha256-3pl7eYRLa9kkmFSBsMGOMQLepBL3ZygNmNqIGP6gdFo=";
    attr = "holesail";
    version = "1.10.1";
    author = "jjacke13";
    mergeReady = false;
  };
  htmd-cli = {
    pr = 510014;
    rev = "17719cc0ea00a2f8a42d086dd3ddc009a9b42193";
    narHash = "sha256-JTFx4kb4J+XhPh4+Slg/5AdDa/JU7ifFM/6PjaIjHO4=";
    attr = "htmd-cli";
    version = "0.5.1";
    author = "drawbu";
    mergeReady = false;
  };
  hunk = {
    pr = 517626;
    rev = "126b7eec4bf5eae2092909a30f699c26a5ecca9e";
    narHash = "sha256-EAPacr+Yk7FhGcQBJK+8Hp1Ed76BYLI1Ym7KMI/C+bk=";
    attr = "hunk";
    version = "0.12.1";
    author = "MarkusZoppelt";
    mergeReady = false;
  };
  hyprland-preview-share-picker = {
    pr = 518025;
    rev = "04e177eb782bc8f724c85b5d0e4ce5654868dcb9";
    narHash = "sha256-mF3MuOBiy4dZyRDvuH/7d7RClEFdEnvT/aCenhw8/+Y=";
    attr = "hyprland-preview-share-picker";
    version = "0.2.1";
    author = "sophronesis";
    mergeReady = false;
  };
  hyprmod = {
    pr = 505419;
    rev = "3909bec5ebe2fa6842c0fc11231d12e0604f521b";
    narHash = "sha256-STXlTg4bub48ZKAn9ZPkTcaGZbsryDEaU3Oi05RVMTU=";
    attr = "hyprmod";
    version = "0.2.0";
    author = "sophronesis";
    mergeReady = false;
  };
  hytale-launcher = {
    pr = 479368;
    rev = "295d057a91b95e48aa85d90d4e8d8312b3e2785b";
    narHash = "sha256-okktIgnA37f0K4gOgzAikT1H62y8i6FV/GO1eyRCFJI=";
    attr = "hytale-launcher";
    version = "2026.03.03-a4f6003";
    author = "karol-broda";
    mergeReady = false;
  };
  icey = {
    pr = 504863;
    rev = "244bcfa14f92a37d8289c1f58a33aee3f3f049cb";
    narHash = "sha256-ip5jzo6YO9nLybzQaARjHkbhbdqZmkWFjTJzjy/G14g=";
    attr = "icey";
    version = "2.4.5";
    author = "auscaster";
    mergeReady = false;
  };
  ida-pro = {
    pr = 504229;
    rev = "00bbbaeebe4faed693ef157aa95c135b774a2357";
    narHash = "sha256-DuSn+rV6XHcNfK7oLtzP6cjMJxCXToAV0uqCFk3mlmc=";
    attr = "ida-pro";
    version = "`9.2.250908`";
    author = "yanmaani";
    mergeReady = false;
  };
  igf = {
    pr = 504271;
    rev = "40eb3c1e665fa7505fd0dd798c6a88b861fa23d0";
    narHash = "sha256-LYjBnb2hlNPQyJ4bEnb9KZ0eqJUWdMmZGv89xw8g6Ck=";
    attr = "igf";
    version = "1.1.2";
    author = "caverav";
    mergeReady = false;
  };
  iloader = {
    pr = 492692;
    rev = "41a0c07518024d38f3da26fdaafc4b697639f9cf";
    narHash = "sha256-LH7K2CsADWgKHfDKv+L7aq/amAweWjVICkqiKDWBb+U=";
    attr = "iloader";
    version = "2.2.4";
    author = "ern775";
    mergeReady = false;
  };
  init = {
    pr = 504963;
    rev = "2fcf96ce201e537b3ac9542ccb2707bf80e45ae2";
    narHash = "sha256-3m2swYIJG3S1nI7juhA1SNs0ssn4EfZorf0DU0sj9/M=";
    attr = "init";
    version = "";
    author = "asakura";
    mergeReady = false;
  };
  inngest = {
    pr = 513849;
    rev = "2a692a021d09edd83cbbd25b4eb19560ec504e68";
    narHash = "sha256-LU4e0QIQf1gMRSEQWoRsEgYDTblptaiBlRtbM5jpWJA=";
    attr = "inngest";
    version = "1.19.2";
    author = "KiKoS0";
    mergeReady = false;
  };
  iqmol = {
    pr = 522151;
    rev = "229f9c52be7b5a1666718eef4239de11eee9396a";
    narHash = "sha256-Ske5Q1qhj6k4trBL6e3U+RhyiS5c7nnbVtfyLyhhSD0=";
    attr = "iqmol";
    version = "3.2.2";
    author = "Usu171";
    mergeReady = false;
  };
  ir-datasets = {
    pr = 440120;
    rev = "21ddee55481536021befcd7cf0566179600b13c3";
    narHash = "sha256-+ry+0hdOA/y950igpg3NaqHcnaY8XgXGPQ6lr+AqqAk=";
    attr = "ir-datasets";
    version = "";
    author = "Gurjaka";
    mergeReady = false;
  };
  jaeger = {
    pr = 512257;
    rev = "2e8a64a5a16b9df2e003e46ac822362bb26bf4cc";
    narHash = "sha256-MGP4crghFmLRlKQSFI41BePDjmPuy0qkUy7i8DofwF8=";
    attr = "jaeger";
    version = "2.17.0";
    author = "jonhermansen";
    mergeReady = false;
  };
  jj-run = {
    pr = 461371;
    rev = "3ec6a7f2d2ff822985def90201a2126df7fc4c6a";
    narHash = "sha256-6JfKO/aeOAgr45mAoVdupahA0t8MGiAPnntsD6XRMy0=";
    attr = "jj-run";
    version = "7";
    author = "NobbZ";
    mergeReady = false;
  };
  jmc = {
    pr = 515133;
    rev = "2881e872f4ef170f9101f228328a417466680ed1";
    narHash = "sha256-ZxisWFr8SDzBhoVrpl9ewC62VCcJzN/kn6zUQZiQwkk=";
    attr = "jmc";
    version = "9.1.2";
    author = "gkaganov";
    mergeReady = false;
  };
  jportaudio = {
    pr = 439674;
    rev = "1473e44d5c619d2a26e5f3c030890e8188015d06";
    narHash = "sha256-GgiLD7XoHTkQ0398Vx93hBhzrhlTeh/i5x1wZ5GoeB4=";
    attr = "jportaudio";
    version = "0-unstable-2025-10-24";
    author = "MiyakoMeow";
    mergeReady = false;
  };
  jqjq = {
    pr = 507192;
    rev = "4486395faadecf2ce7abdae4db1317b6a876a952";
    narHash = "sha256-87aQesK1+pfn4W7nJ53Dsp7LRGVlYWDk5bUPBO+/6IQ=";
    attr = "jqjq";
    version = "0-unstable-2026-03-30";
    author = "yzhou216";
    mergeReady = false;
  };
  karedi = {
    pr = 513801;
    rev = "17bfba7de5e2135fb54bc0e585fe77085add70d9";
    narHash = "sha256-a/ZyhDeXm1HA10tDxnzHgcQONGw2cbHRooXXZdnawzM=";
    attr = "karedi";
    version = "1.8.0";
    author = "RemuSalminen";
    mergeReady = false;
  };
  kb-python = {
    pr = 438016;
    rev = "02d525b28aaefa669a09617d74d2c56e2b033778";
    narHash = "sha256-jjJn0+ksfdz0iheFcputn7Wr5A1kjejnenodioydwcg=";
    attr = "kb-python";
    version = "0.30.1";
    author = "Kupac";
    mergeReady = false;
  };
  kiorg = {
    pr = 506181;
    rev = "21882aeffad347ee74db997123fbbcf4e52248ce";
    narHash = "sha256-nup9HXDT0nsljfNzWJIW90jpdoikmuRbNyhxT7WExyU=";
    attr = "kiorg";
    version = "1.5.2";
    author = "ambroisie";
    mergeReady = false;
  };
  kubernetes-mcp-server = {
    pr = 512939;
    rev = "1161c24a5e175ddec62c47cce1d45414113243e7";
    narHash = "sha256-+hbpQLj+VpSVXRiUgMeTNa+ERihZAsLBOscvaUJEKvM=";
    attr = "kubernetes-mcp-server";
    version = "0.0.60";
    author = "dudeofawesome";
    mergeReady = false;
  };
  lampghost = {
    pr = 439591;
    rev = "17a544d220351550fcb673b79e1ab25c0c54bf57";
    narHash = "sha256-Kd4vT0iMgaSiZ4YB1bxmdq5zz9tqt/xkPpf3cpxvMo4=";
    attr = "lampghost";
    version = "0.3.1";
    author = "MiyakoMeow";
    mergeReady = false;
  };
  larksuite = {
    pr = 492376;
    rev = "08d03995143f352ba8e7b897cf14f43352f2ed4d";
    narHash = "sha256-z/7ychqrngbUfG9bKCy2pkHy0JSaj+ZDYlbPBeaZEiU=";
    attr = "larksuite";
    version = "7.59.12";
    author = "adamcolwell";
    mergeReady = false;
  };
  lazylibrarian = {
    pr = 423722;
    rev = "2ca38038bdbd9cbfaf22f52b48c5e178ceea0b9f";
    narHash = "sha256-rjLZIS6gojGKaQNMqXoyZ1Q2unMTwC+ZuoALBSuCH8g=";
    attr = "lazylibrarian";
    version = "0-unstable-2025-07-08";
    author = "Xelden";
    mergeReady = false;
  };
  lazymake = {
    pr = 520735;
    rev = "042e1bf0afbce176a62443e6ea2b41c4870b6ea2";
    narHash = "sha256-s2fY1Cr/nfRhwAL2NLvDuJ36ceRXsdBYOx5kLWs6rC0=";
    attr = "lazymake";
    version = "0.4.1";
    author = "kpbaks";
    mergeReady = false;
  };
  leantime = {
    pr = 487681;
    rev = "31e4c04a97e5922a9989813b2e70d8cdbbb65838";
    narHash = "sha256-eNnNo7uMpyf5baNXG20s8KjAwyzULAgWqlsQLuJc2pg=";
    attr = "leantime";
    version = "";
    author = "jordycoding";
    mergeReady = false;
  };
  lemonade-ai = {
    pr = 498314;
    rev = "1486c80d488e0d023adea3275bc1b052e528c448";
    narHash = "sha256-sVFzdeeAlmFgTWY1EUSlKyml6rZzqn0FHJ+IpYHag10=";
    attr = "lemonade-ai";
    version = "";
    author = "Videl";
    mergeReady = false;
  };
  libgsystemservice = {
    pr = 518607;
    rev = "284cb47b65d72e12b01954bc17ba0fdf4ecebc04";
    narHash = "sha256-xgeI7WtioXdo0fV+DH5eTFMz5JNk5Ryxge6apuAqPfk=";
    attr = "libgsystemservice";
    version = "0.3.0";
    author = "tbutter";
    mergeReady = false;
  };
  libremd = {
    pr = 519187;
    rev = "0246a74ab400f9f7fe5f8857960236f445f13429";
    narHash = "sha256-DilOMMv5GQ70uJR4+M3NlxU7mwcU7A3v9L5jnPU2JPQ=";
    attr = "libremd";
    version = "4.5.0";
    author = "philocalyst";
    mergeReady = false;
  };
  libtinfo5 = {
    pr = 507359;
    rev = "2986882eb46a6ce3d0dbcc1a17def6959d4a9419";
    narHash = "sha256-oHaYvxj7LThjcsJc+sn2uLuBGvRfK10UVhWEz4RozFg=";
    attr = "libtinfo5";
    version = "5.9";
    author = "zane-weissman";
    mergeReady = false;
  };
  libtinfo6 = {
    pr = 507359;
    rev = "2986882eb46a6ce3d0dbcc1a17def6959d4a9419";
    narHash = "sha256-oHaYvxj7LThjcsJc+sn2uLuBGvRfK10UVhWEz4RozFg=";
    attr = "libtinfo6";
    version = "6.6";
    author = "zane-weissman";
    mergeReady = false;
  };
  linkstack = {
    pr = 428890;
    rev = "4aa02d33270c5aa1d606ef465a92e3f9f9619c81";
    narHash = "sha256-XeoFKmqRveM8WMmR9oe7XyriwwdwBjUXaS2o/BHzkZc=";
    attr = "linkstack";
    version = "4.8.4";
    author = "j0hax";
    mergeReady = false;
  };
  lswmi = {
    pr = 429057;
    rev = "106f7cde7cc637e427582af33de5004b38c6cacf";
    narHash = "sha256-w9gPqqlQfz8UNOVdRVcikJAxW6QWrJI0X3TRZunbf34=";
    attr = "lswmi";
    version = "1.2.0";
    author = "nikableh";
    mergeReady = false;
  };
  lulu = {
    pr = 517792;
    rev = "097bc92dee5a3acc370b19c4356fc8533891884d";
    narHash = "sha256-j1izFBa6CupiFnppdWdIkXMGEXaPBiegiEp0ygbylVk=";
    attr = "lulu";
    version = "4.3.1";
    author = "philocalyst";
    mergeReady = false;
  };
  mail-archiver = {
    pr = 501428;
    rev = "4303900ea4d498f4699f673c9727f1a53f063d84";
    narHash = "sha256-WLils0OsfUd9YZ4kznKrsC8cxkJNTCuF6+BCH9X4HGM=";
    attr = "mail-archiver";
    version = "2603.1";
    author = "pyrox0";
    mergeReady = false;
  };
  maven_4 = {
    pr = 516100;
    rev = "04201da237c4ab1702786c14ae9c79e719040472";
    narHash = "sha256-i9lIfxu06wD26igkE4qFP/brElrlh83XvQm7dORJnKU=";
    attr = "maven_4";
    version = "4.0.0-rc5";
    author = "britter";
    mergeReady = false;
  };
  mcg = {
    pr = 509402;
    rev = "0893d32cfecc4bf6434822b397991f6ec9a3ebf8";
    narHash = "sha256-lWfVYq8MV33tiroQcrVnOVeXcwZOl2l8/RjaigblrRk=";
    attr = "mcg";
    version = "4.0.2";
    author = "jfly";
    mergeReady = false;
  };
  mcmojave-cursors = {
    pr = 516977;
    rev = "2fd13d46e1922bc8f022f6219caf4463506b7758";
    narHash = "sha256-ST1evvpoZ1SndCEmSUgVsaAgMp5SG4fJebEJ8nhOzu8=";
    attr = "mcmojave-cursors";
    version = "0-unstable-2026-05-05";
    author = "cooukiez";
    mergeReady = false;
  };
  mcp-gateway = {
    pr = 489276;
    rev = "46bcf9a43a57ea4d24f49f301807c37a6f9693ad";
    narHash = "sha256-fcLtseL0cBLy1/STWyYPoi6ZE32LayZER50DTYkvvG0=";
    attr = "mcp-gateway";
    version = "1.2.0";
    author = "pedrobrantes";
    mergeReady = false;
  };
  metaphlan = {
    pr = 504118;
    rev = "107a1cc8ff42bec153932166029220d5205c4cb3";
    narHash = "sha256-OjPVi9HJ/vgKEhWSH2QlmnFNLcM6Y1cLTY87imxSO+E=";
    attr = "metaphlan";
    version = "4.2.4";
    author = "artur-sannikov";
    mergeReady = false;
  };
  metube = {
    pr = 508774;
    rev = "12eb49cd1d1ad936882c53db0994355a0b9f7db5";
    narHash = "sha256-5YAjZ837tL0+mFNsw4djwXYYAQAJe+fWuaVLBCT790c=";
    attr = "metube";
    version = "2026.04.09";
    author = "hunterwilkins2";
    mergeReady = false;
  };
  mgccli = {
    pr = 500774;
    rev = "3172c13e8b630eb480ecf93dfc5ad5c6b3d052fd";
    narHash = "sha256-mTUdwgc1YE4CF1vAjr9T3NkG+C8XcU1US3+OBbAGSnM=";
    attr = "mgccli";
    version = "0.55.0";
    author = "fabiob";
    mergeReady = false;
  };
  microcad = {
    pr = 491431;
    rev = "2916a825307a024e87dd7d2c5bc8cfc4895ff78d";
    narHash = "sha256-fVPHMyI32Ypn8IUPWEDIUtWDNT5fbs6/++sXxfQle4o=";
    attr = "microcad";
    version = "0.5.0";
    author = "Guelakais";
    mergeReady = false;
  };
  motioneye = {
    pr = 507719;
    rev = "2a4ecc85f05c14a4fe4e3e1cfc63c3c78dba16db";
    narHash = "sha256-R+OmMJqREnCXRMTo3m1EI2qsNJwi7jTBUoK0batm7mg=";
    attr = "motioneye";
    version = "0.43.1";
    author = "nixpkgs-ci[bot]";
    mergeReady = false;
  };
  mpm = {
    pr = 506150;
    rev = "009fb06992a8837657fcaf7c1148e9d81b197341";
    narHash = "sha256-WeW9VOB+Kvo05qvi59JkFK6hbThTrmtefK+Iw4T8kQc=";
    attr = "mpm";
    version = "2026.3";
    author = "djmaxus";
    mergeReady = false;
  };
  multi-scrobbler = {
    pr = 519119;
    rev = "2aa26fa03e86b1a6621141f16328f52dc35777b3";
    narHash = "sha256-DQTqzQziP++AyyrzphmAi6BZyG7BhcttUjjnGIQyYAg=";
    attr = "multi-scrobbler";
    version = "0.13.3";
    author = "philocalyst";
    mergeReady = false;
  };
  nautilus-admin-gtk4 = {
    pr = 489094;
    rev = "20a6d702692026abe2abea8a260f74c478d9e362";
    narHash = "sha256-C6olfBtTOt92lWKYNLZarhhMojjqnBeO/YawQVY2ml8=";
    attr = "nautilus-admin-gtk4";
    version = "1.2.0";
    author = "Verantor";
    mergeReady = false;
  };
  netsleuth = {
    pr = 413976;
    rev = "47c53e5a868a4c97ce96b4582b134da9ac94a935";
    narHash = "sha256-GX5PtzNdFe14YJOnrD24lj3A6K6KQt67ACbKU4y4CSI=";
    attr = "netsleuth";
    version = "1.1.4";
    author = "Cameo007";
    mergeReady = false;
  };
  netwatch = {
    pr = 510347;
    rev = "43e4a9f0df614e50371acb53d2247ef9c08eb0ab";
    narHash = "sha256-ZL7931mlrnYnss5IS6fVJSWDvREH/i14+xoiSOOCBNY=";
    attr = "netwatch";
    version = "0.11.1";
    author = "blemouzy";
    mergeReady = false;
  };
  nibbler = {
    pr = 512882;
    rev = "2b4df41e03f7fc88797352421961afaec8b1ffc0";
    narHash = "sha256-FC+ZCADF3qNi+Hswc2p9eWI/tQqNM3K73sqnxgBPjZA=";
    attr = "nibbler";
    version = "2.5.8";
    author = "oati";
    mergeReady = false;
  };
  nix-post-build-hook-queue = {
    pr = 490792;
    rev = "02801b0c3aa6c9c8a8c4578a36bd9d9ef185a673";
    narHash = "sha256-Q9oC7Wa0pB3XcoOJzyULDFuCXxlrQpHRPFEhvXJuk1U=";
    attr = "nix-post-build-hook-queue";
    version = "1.1.0";
    author = "newAM";
    mergeReady = false;
  };
  nocturne = {
    pr = 522380;
    rev = "0de7dbe1651fb62ca88727f8b110df40b8538499";
    narHash = "sha256-YRtcQ+pTYVHzPAb584G3NLQxrUCTagl337rKz3GY2Tw=";
    attr = "nocturne";
    version = "1.1.1";
    author = "pbsds";
    mergeReady = false;
  };
  nokolexbor = {
    pr = 508922;
    rev = "47969af99c23b33e3d7566d5bdc7cd48d57765a8";
    narHash = "sha256-iqM58mX8uowuau8TJM6GksllaUpqid7d+s7ycYvN9zo=";
    attr = "nokolexbor";
    version = "0.7.0";
    author = "smithtim";
    mergeReady = false;
  };
  nomad_2_0 = {
    pr = 512753;
    rev = "0d56703d1e6365ed26b442ba0630be3f6d9cbe98";
    narHash = "sha256-LuvlegQaHLH5w2CuKJt4QeUiXfsuIpH8sv9VwVKPZxA=";
    attr = "nomad_2_0";
    version = "2.0.0";
    author = "adriansalamon";
    mergeReady = false;
  };
  ntfyr = {
    pr = 513415;
    rev = "37dd5cd044b33ad14c2751190cd58285f2758e07";
    narHash = "sha256-Osl4XEbGSD51gt8oY75Ygd3TeMiVh88fi/wZShmtt9E=";
    attr = "ntfyr";
    version = "0.5.3";
    author = "Joaqim";
    mergeReady = false;
  };
  obs-pwvideo = {
    pr = 509289;
    rev = "017ec1a180f455a97c88155ec38f9603f865c730";
    narHash = "sha256-feDKwqfXtshOumVLvHAAEscyiNcOGQYZgIcblZJFNys=";
    attr = "obs-pwvideo";
    version = "0.2.4";
    author = "liquidnya";
    mergeReady = false;
  };
  octelium = {
    pr = 491553;
    rev = "2294c16f65c3ef2df1be36b4d447ecc35bd35e20";
    narHash = "sha256-yl/nY1Ku7BlGtlpI3GcCVDIwDeMaLKM/r5RFYTatX5c=";
    attr = "octelium";
    version = "0.27.0";
    author = "evanlhatch";
    mergeReady = false;
  };
  omniwm = {
    pr = 515530;
    rev = "3c90055948b67bf407972e505f28853f4a548f65";
    narHash = "sha256-tR7+BBVavORmSgtTjCW7+8larl2WOHhIeEu7jS4e4Iw=";
    attr = "omniwm";
    version = "0.4.7.4";
    author = "mmfallacy";
    mergeReady = false;
  };
  oneMath = {
    pr = 514640;
    rev = "474a6fd5224dab131bfffaab602416d5b4263353";
    narHash = "sha256-KWWBxplKn/aFAWuQJyhpPlV8pVs3dAeKpQTCnpuL+G4=";
    attr = "oneMath";
    version = "0.9";
    author = "kilyanni";
    mergeReady = false;
  };
  open-numismat = {
    pr = 509322;
    rev = "0c2e70690b1cd5fee38ffedaf6fa330f6c5e7cd5";
    narHash = "sha256-7qpwZPrVOsAOwrC4BPIbCegaIDHeM2FN5Pn6fk3pWlo=";
    attr = "open-numismat";
    version = "1.10.5";
    author = "malikwirin";
    mergeReady = false;
  };
  openjdk26 = {
    pr = 506259;
    rev = "1f7498329c67cc79908c0600cecabeffdaa1498d";
    narHash = "sha256-4s1lmmr1h/2MTS4yvozg8/mLhDxxTQldApLBh1ohPOk=";
    attr = "openjdk26";
    version = "26-ga";
    author = "Ring-A-Ding-Ding-Baby";
    mergeReady = false;
  };
  openttd = {
    pr = 521793;
    rev = "16803d5ae4e9992280cfee879d8426175b79ed5d";
    narHash = "sha256-JXeNJDAGxDqfb7jasB+vXByVLbRp9nEAKK7KA4P5iLM=";
    attr = "openttd";
    version = "";
    author = "philocalyst";
    mergeReady = false;
  };
  openwhispr = {
    pr = 520102;
    rev = "436987e0263dfe1358c741b53398f2596397fb68";
    narHash = "sha256-foUGetqBBOL7CngIkXsPlikHKmxktuQIuPhyXRicdpM=";
    attr = "openwhispr";
    version = "1.7.0";
    author = "benedikt-weyer";
    mergeReady = false;
  };
  orioledb = {
    pr = 513940;
    rev = "38ee3fc18c913eb7e51e91cc875e2adf6f1309e8";
    narHash = "sha256-dAl+wXh8DuEaRSEQQsqtMJusPcs4frN7ZcIdw2CyqXY=";
    attr = "orioledb";
    version = "";
    author = "wolfgangwalther";
    mergeReady = false;
  };
  partydeck = {
    pr = 522351;
    rev = "38fb863dc75982308a31e9cd9d066ec294717507";
    narHash = "sha256-Ug8q/lNuQ/nNMt1/pdzc0LFcfCAHjjuDIqbBJplCcgE=";
    attr = "partydeck";
    version = "0.8.6";
    author = "colonelpanic8";
    mergeReady = false;
  };
  pathplanner = {
    pr = 499329;
    rev = "402cbbd6fce0d98489f2f3c4641e42a50d0cfaef";
    narHash = "sha256-a4e5xPofkQYBQ4Dp6RGXAskGQTIFJX81o0g0FnHlhmA=";
    attr = "pathplanner";
    version = "2026.1.2";
    author = "colepearson27";
    mergeReady = false;
  };
  pdudaemon = {
    pr = 514361;
    rev = "1270df7b528db9dc9ac2a0001468cbd6c7c338a1";
    narHash = "sha256-jJgkbZ3FLe2iMHOqbJy+fTnbQOQ7lnBUal3cukFBSbM=";
    attr = "pdudaemon";
    version = "1.1.1";
    author = "AiyionPrime";
    mergeReady = false;
  };
  peertubePlugins = {
    pr = 474874;
    rev = "492c3bc9fd9af3cd49d21ac5ac29aa7942d8901b";
    narHash = "sha256-9DlEgn05obKK4LQaZoIZYElv4o9lw/Mq5k3hY47dV7U=";
    attr = "peertubePlugins";
    version = "";
    author = "ethancedwards8";
    mergeReady = false;
  };
  pesde = {
    pr = 512280;
    rev = "1021584703a5f6231b0d2a9eb0eac6214f031773";
    narHash = "sha256-YsfiR21uBRzn+kMcM+P+6685BCzVa0Dp4ft2YRN90DE=";
    attr = "pesde";
    version = "0.7.3";
    author = "vokinn";
    mergeReady = false;
  };
  phonopaper-cli = {
    pr = 510595;
    rev = "1b689131cb2a04b72c5d29f01cd6449d8b23e170";
    narHash = "sha256-dMGmD0EFoTC6O8xP5bKULKs9eG8HDH8zl5X57htB7fs=";
    attr = "phonopaper-cli";
    version = "0.1.0";
    author = "samueltardieu";
    mergeReady = false;
  };
  polymc = {
    pr = 461881;
    rev = "15da68886e21f60f08814ca7fd1702e1db142f6d";
    narHash = "sha256-XHLbTi+Q6PwTw9AB++SeBLDeDgaJZJ3VgjvpCpmQSbI=";
    attr = "polymc";
    version = "7.0-unstable-2025-11-15";
    author = "hustlerone";
    mergeReady = false;
  };
  pq-parquet = {
    pr = 520394;
    rev = "451d1252f64f9abfcd60c2aad6c5dd098a51c46b";
    narHash = "sha256-JaHGjK1D4afZno93L3/Fi8XAeYa3xFKd+XyY2JElzFQ=";
    attr = "pq-parquet";
    version = "1.0.8";
    author = "xiaoxiangmoe";
    mergeReady = false;
  };
  prometheus-rtorrent-exporter = {
    pr = 511086;
    rev = "12f3c8db538fc62be9d4a33219a20b347feab711";
    narHash = "sha256-fjK5lnDZHjK1PFwEByPU/8WAeufhVxf8zXDGdZxjdi0=";
    attr = "prometheus-rtorrent-exporter";
    version = "1.7.0";
    author = "ananthb";
    mergeReady = false;
  };
  proxyt = {
    pr = 521890;
    rev = "1c9b2b56d5453492b179a32e7c70ef345b042ece";
    narHash = "sha256-5Y1xRhL5d8YJ71kei00u/4D/lcWdzxTPAgN1BGC6Wtc=";
    attr = "proxyt";
    version = "0.0.6";
    author = "NyCodeGHG";
    mergeReady = false;
  };
  pumpkin = {
    pr = 512627;
    rev = "2078458bf3d00ecfb7e0c537039c36bef49de278";
    narHash = "sha256-vXt/8WOy1cdKto6QXWFMPyqkKGK8MlBpUTd8Vg1gZU8=";
    attr = "pumpkin";
    version = "0-unstable-2026-03-05";
    author = "philocalyst";
    mergeReady = false;
  };
  qml-language-server = {
    pr = 515608;
    rev = "16c29d85ebc620c4e52980f1f2d0ce2a4898d426";
    narHash = "sha256-J7fKTUJkq01IUfe4DDHheG3M/xtoTxcN8IPTkm80+js=";
    attr = "qml-language-server";
    version = "1.7.0";
    author = "pyrox0";
    mergeReady = false;
  };
  quake-shareware = {
    pr = 501176;
    rev = "1fdca2228733606c36121b1780ca4d6252b2806d";
    narHash = "sha256-JxMLJ9nIgPh+C6pte+Q78wBPS5A1SuQrFYUUfkmMpU4=";
    attr = "quake-shareware";
    version = "1.06";
    author = "axunes";
    mergeReady = false;
  };
  quien = {
    pr = 509321;
    rev = "17a3aaa92fb059297ce819d9e324c679f8f0519f";
    narHash = "sha256-K5AI4BEIzvi0LJogLTxM4HpktH8Xl6ZfHUw2wLi744M=";
    attr = "quien";
    version = "0.9.0";
    author = "Myzel394";
    mergeReady = false;
  };
  raiderio-client = {
    pr = 510344;
    rev = "1b80855b1265c4fad87373af7863bf39a6d847b7";
    narHash = "sha256-hMxqxUdLCZoRiOsW8cs/u/Q74lMDP0pfFIYWpmMLwsE=";
    attr = "raiderio-client";
    version = "4.10.7";
    author = "Gako358";
    mergeReady = false;
  };
  rapina-cli = {
    pr = 512111;
    rev = "21ceb12152c19bf16fee36a636f1baa7615d6ac6";
    narHash = "sha256-verzKOEQhA0IB/8hnfwCjuy+8UimnrSxGQHPjoIIKR4=";
    attr = "rapina-cli";
    version = "0.11.0";
    author = "apetrovic6";
    mergeReady = false;
  };
  ratpoison-sloppymove = {
    pr = 517112;
    rev = "044bb90f757797d8f37190f51e6d01ab94de81fe";
    narHash = "sha256-M8NxInL0RxHduqgO6IFs/26MHUGhojP0ZnPRo61HJvk=";
    attr = "ratpoison-sloppymove";
    version = "1.01";
    author = "turtley12";
    mergeReady = false;
  };
  re-arranged-pixel-dungeon = {
    pr = 457700;
    rev = "3ff75f469cba27de09c05aa19a04b6ce6785f762";
    narHash = "sha256-TPbfIFtdSJtCq1hAonwH1sNLTZBZSS3GQA0rkrJjOzE=";
    attr = "re-arranged-pixel-dungeon";
    version = "3.39.0";
    author = "zirancumin";
    mergeReady = false;
  };
  repeater = {
    pr = 515274;
    rev = "270ecfb674e020b7e94c20f37e10c18f4fc70684";
    narHash = "sha256-tBoGMai2EfQ4TEDqCc/apsYHsvEaWxe7NdmbyUOhgVo=";
    attr = "repeater";
    version = "0.1.9";
    author = "gwg313";
    mergeReady = false;
  };
  retrom = {
    pr = 516038;
    rev = "2f74d2cec3f15889979ba5d631cd621652a5dcf7";
    narHash = "sha256-JqMZsku7dTVt/tUNRKZP8+PJfR676wHqmQKTYwJ23XM=";
    attr = "retrom";
    version = "0.8.1";
    author = "ConcurAc";
    mergeReady = false;
  };
  retrom-service = {
    pr = 516038;
    rev = "2f74d2cec3f15889979ba5d631cd621652a5dcf7";
    narHash = "sha256-JqMZsku7dTVt/tUNRKZP8+PJfR676wHqmQKTYwJ23XM=";
    attr = "retrom-service";
    version = "0.8.1";
    author = "ConcurAc";
    mergeReady = false;
  };
  rig = {
    pr = 458304;
    rev = "044b684b71e9ae48b17a6ca53567362dacce6c9a";
    narHash = "sha256-0Wrab4XHnAv6nS6Ey6myFXWZRhuwqIqXIKuBqRB8apo=";
    attr = "rig";
    version = "0.7.1";
    author = "giang-nghg";
    mergeReady = false;
  };
  roblox = {
    pr = 491420;
    rev = "1e78819174a0aac529baa1f50a01f255ca03056f";
    narHash = "sha256-3ue26BxF0Eu5YG/EayoT/3eBEEBKIebIU15uOEAcDws=";
    attr = "roblox";
    version = "0.717.0.7170982";
    author = "Eveeifyeve";
    mergeReady = false;
  };
  robloxapid = {
    pr = 462157;
    rev = "35ed3b29522bdd96714cc339b491a47eed01bd22";
    narHash = "sha256-B5JqJxY4/aqT1DjO2aTV8jhQo37oFcaXjIwqNbHoB/o=";
    attr = "robloxapid";
    version = "0.0.16";
    author = "t7ru";
    mergeReady = false;
  };
  rustlock = {
    pr = 509053;
    rev = "3d0b576e7509d0b2bff59a6cd6504a3e61c8d297";
    narHash = "sha256-BuTLnwKumbRBgU6d2pvm89hlnopDM+TBOVhQSCO3LLE=";
    attr = "rustlock";
    version = "1.1";
    author = "JorySeverijnse";
    mergeReady = false;
  };
  rvgl-launcher = {
    pr = 501666;
    rev = "4033cff6784e9d87f0a1b75df594c78e06d2f02b";
    narHash = "sha256-kdXtLMqK07hF9rfNaPyOkjOFPsNHxdrkxYQQVlKA3jk=";
    attr = "rvgl-launcher";
    version = "0.1.23.1030a4-rev1";
    author = "andrew-field";
    mergeReady = false;
  };
  ryubing-canary = {
    pr = 520808;
    rev = "0f925e32488ae5da1ad8b4841da624ff13f4a4d8";
    narHash = "sha256-BD+02/l8AlqF5FzVHK5Rx2RJLDzVaPop7++UHxSNU3Q=";
    attr = "ryubing-canary";
    version = "1.3.287";
    author = "Swofty-Developments";
    mergeReady = false;
  };
  saa = {
    pr = 510096;
    rev = "1d5f700dcc72002f251ef899ddd0e226aaefdb94";
    narHash = "sha256-tnDJf6lF2MW273vzue93sQcGSAixEZTonDz9kck5Qlw=";
    attr = "saa";
    version = "1.5.0";
    author = "youhaveme9";
    mergeReady = false;
  };
  satochip-utils = {
    pr = 402608;
    rev = "2378e48a952d03fe7f17a120e3ff62007922d6c7";
    narHash = "sha256-VH8kjrIhPBMkUJQoa/bmsC2MpDY+ienAP1aGBRfZHQE=";
    attr = "satochip-utils";
    version = "0.4.0-beta";
    author = "hatch01";
    mergeReady = false;
  };
  semcode = {
    pr = 519458;
    rev = "2ac677fa0d2f3aea7275a61adecdbf5884df223d";
    narHash = "sha256-mPLb2hzqzNxe39+/rOxweJv81PZcSNirrOA1RH5vz4U=";
    attr = "semcode";
    version = "0.1.1";
    author = "RazeLighter777";
    mergeReady = false;
  };
  shellshot = {
    pr = 520363;
    rev = "24caf58eacd2e86758e2a16c6bffcd706ad344df";
    narHash = "sha256-O+wouu/pDLB7R6mo2Wleh3XhO51qiIo28+w68S4e1io=";
    attr = "shellshot";
    version = "0.5.0";
    author = "kpbaks";
    mergeReady = false;
  };
  snipt = {
    pr = 468877;
    rev = "1185234e5272fdf3cffd90b149215adc2c6006aa";
    narHash = "sha256-RroLo94AhWM78T9APdYhCNlQRX5iYRSQlMToS0O6Ehw=";
    attr = "snipt";
    version = "0.1.0";
    author = "chillcicada";
    mergeReady = false;
  };
  socalabs-piano = {
    pr = 461894;
    rev = "38f669c3202fd319dbefcd94094340162d6d587a";
    narHash = "sha256-XEe3eGsPnZquLdYtxATk/5f9/CXaGVsbsMmGdttBFO4=";
    attr = "socalabs-piano";
    version = "0-unstable-2025-11-20";
    author = "mrtnvgr";
    mergeReady = false;
  };
  sonar = {
    pr = 501774;
    rev = "3742450c091f35277b9a8fa9acfc842056b902e2";
    narHash = "sha256-kz3jmEi/ka7SXPItpK6cO8rQiwpG902DFm8d2j82Kf4=";
    attr = "sonar";
    version = "0.2.9";
    author = "pbek";
    mergeReady = false;
  };
  sonarqube-cli-bin = {
    pr = 518079;
    rev = "1b8f4ec98625d32a17ee0b48fa3b01a63a2feae8";
    narHash = "sha256-FI01I3f5I8iImiyURxPc+4wzlduORGV8+bMVFggGSmw=";
    attr = "sonarqube-cli-bin";
    version = "0.11.0.1439";
    author = "steveej";
    mergeReady = false;
  };
  speedtest-exporter = {
    pr = 467982;
    rev = "1c16ac6a48b5965e8df176c7e47d41d5bf5a0caa";
    narHash = "sha256-5Iy13b+AJ9K5IxFH026VW0JbZ3pgO7I5DR3D4A6kuBY=";
    attr = "speedtest-exporter";
    version = "1.1.4 + nixos/prometheus-exporters: init speedtest-exporter";
    author = "emaiax";
    mergeReady = false;
  };
  spell-cli = {
    pr = 521276;
    rev = "3b6248d675f92f692debe88261cad6300e8142bb";
    narHash = "sha256-0rGwWuDN95U0d9ioYRwsRYe9I4RjwCUUYtcJSIsRn1s=";
    attr = "spell-cli";
    version = "0-unstable-2026-05-17";
    author = "onatustun";
    mergeReady = false;
  };
  spelling-bee = {
    pr = 520874;
    rev = "1f77415f719d0f2168e092936174b940a9406f24";
    narHash = "sha256-1yFLAxysqIExd+hRS4h/j2ZUgzxCFsLJhQ2ysP6VT4I=";
    attr = "spelling-bee";
    version = "0.1.5";
    author = "3nln";
    mergeReady = false;
  };
  spout2pw = {
    pr = 509289;
    rev = "017ec1a180f455a97c88155ec38f9603f865c730";
    narHash = "sha256-feDKwqfXtshOumVLvHAAEscyiNcOGQYZgIcblZJFNys=";
    attr = "spout2pw";
    version = "0.2.3";
    author = "liquidnya";
    mergeReady = false;
  };
  stb = {
    pr = 491159;
    rev = "3bb33b543254210beb152bc79a341cfddc89dde9";
    narHash = "sha256-Ws6dNpsbDoqZ4O6v/3+5lDdG0DnAGrQm25LjfGEoykA=";
    attr = "stb";
    version = "";
    author = "JulHee";
    mergeReady = false;
  };
  stef = {
    pr = 460347;
    rev = "4cda59f12b47f7deab0725e28bed9932822750bc";
    narHash = "sha256-I24dyDTjsSp5/IdJHkOFsGbyU/jRKFAuM1dAD6X8PfA=";
    attr = "stef";
    version = "1.0.9";
    author = "ueuie";
    mergeReady = false;
  };
  stochos = {
    pr = 504208;
    rev = "4293b82af41809177e14354816aa7546b201152f";
    narHash = "sha256-OUaoVEkC4tOEH+P6jf2yfXY3lcNGdoXUc5llcdlTMkQ=";
    attr = "stochos";
    version = "0.2.0";
    author = "MrMebelMan";
    mergeReady = false;
  };
  stremio-service = {
    pr = 460557;
    rev = "1955ba843793bdc1812c4eaa7c80aa4800f47e3c";
    narHash = "sha256-hCUvwOTgUfcCeJiYp8jJ+Dap9DpXGI8WgkvxW7IaNVk=";
    attr = "stremio-service";
    version = "0.1.15";
    author = "sparky3387";
    mergeReady = false;
  };
  suitesparsePackages = {
    pr = 486083;
    rev = "48df9de5a69c306b1acd694670bedd90dcabf02b";
    narHash = "sha256-1f9HvEm5U6R0rtNJN5l9wE7JSHPnxnxOPoea1aYArFk=";
    attr = "suitesparsePackages";
    version = "7.12.1";
    author = "qbisi";
    mergeReady = false;
  };
  supertuxkart = {
    pr = 520901;
    rev = "2b2bf308254966d92f497f180d9e192faa02d657";
    narHash = "sha256-e4UBpg98lrCyWosucbWEc5Suj2Uu/nzIDXDauL2gqEc=";
    attr = "supertuxkart";
    version = "";
    author = "philocalyst";
    mergeReady = false;
  };
  sure = {
    pr = 506299;
    rev = "01a9c5e5d786b8d5c3b62a01d8f38a7e35488402";
    narHash = "sha256-/P3BCRRt5EwKsAvA2RyugnYFOiPeGu6l+eBNAxV+UTc=";
    attr = "sure";
    version = "0.6.9";
    author = "pjrm";
    mergeReady = false;
  };
  surge-downloader = {
    pr = 505892;
    rev = "1fce24e4051b032a37b67aa6c0a64b299d8db181";
    narHash = "sha256-V8z+oDtrMDFTElf+F3Zk3eBqFFfddFYIwrx4ckqBASI=";
    attr = "surge-downloader";
    version = "0.7.5";
    author = "crispyfires";
    mergeReady = false;
  };
  tansu = {
    pr = 512110;
    rev = "3a294c8f4c6e3b59e755d723fd424563c98e3671";
    narHash = "sha256-3HDP7YK96WedWPrZCEpCIMCAxzISmIn5t4QA3S5pz1k=";
    attr = "tansu";
    version = "0.6.0";
    author = "jonhermansen";
    mergeReady = false;
  };
  terminal-oscilloscope = {
    pr = 507228;
    rev = "3b75e7c6057c174528380eec8272ed2dc6a0b187";
    narHash = "sha256-5XGmmypznfvV+CVEnlUVVuTtjbKQRdEjBucO808SmaE=";
    attr = "terminal-oscilloscope";
    version = "0.1.0-unstable-2026-04-05";
    author = "sophronesis";
    mergeReady = false;
  };
  threatdeck = {
    pr = 516259;
    rev = "33f26563fe344a26ea723b125fc2df6b9a91e8fa";
    narHash = "sha256-pwAxLrB8mXpRJy4lrh/ViaajfoMtj4Msng3Ngj3yDOA=";
    attr = "threatdeck";
    version = "0.1.3";
    author = "gwg313";
    mergeReady = false;
  };
  thrive = {
    pr = 521762;
    rev = "140c14bbebf367f1022346f2c8d0630aa25788f2";
    narHash = "sha256-ibnitg4ijgpSIK5BoEFWBmPOJqEdIIqbip1ZT1nBB3I=";
    attr = "thrive";
    version = "1.0.1.1";
    author = "philocalyst";
    mergeReady = false;
  };
  thumbor = {
    pr = 442841;
    rev = "3e5ebb749443ae929ffb72dbee481f98ed20fa44";
    narHash = "sha256-hJiOMjjwPWmPZwA2do7qULLsnCXufd4S/yta1i4v9Xg=";
    attr = "thumbor";
    version = "7.7.7";
    author = "sephii";
    mergeReady = false;
  };
  thunderbird-appointment = {
    pr = 515641;
    rev = "3b81d65a60dfe167a1dff3c3a5625394c8786102";
    narHash = "sha256-woowrx9vUVUoiLoDHAoNDtNyxiUnsntwk8D5Cvdx9fI=";
    attr = "thunderbird-appointment";
    version = "1.4.1";
    author = "philocalyst";
    mergeReady = false;
  };
  tidekeeper-cli = {
    pr = 522094;
    rev = "13ab06516b4f9630289e0d7af349068f5e1fa193";
    narHash = "sha256-lvKy94noGWuYTOwtTjXWIdYKcp2W1viOi9ziOfJe+Ao=";
    attr = "tidekeeper-cli";
    version = "v2026.5.15.4";
    author = "Gernomaly";
    mergeReady = false;
  };
  todoist-cli = {
    pr = 517471;
    rev = "0fd25756ed8a38c3d305bc3df7ed8b8ee45fc4b0";
    narHash = "sha256-An6SlpEFalQIFVeOdN8c6UIivjCzdC8qU5lrFIu8WQM=";
    attr = "todoist-cli";
    version = "1.61.2";
    author = "joaosreis";
    mergeReady = false;
  };
  tokscale = {
    pr = 510494;
    rev = "39ad438f22ead07b29edd678e41430f88bf6ed0b";
    narHash = "sha256-QI8+E9gW0P11GB7awcPfid5JVMHbjaugrpE6V0GHngA=";
    attr = "tokscale";
    version = "2.0.26";
    author = "kpbaks";
    mergeReady = false;
  };
  toofan = {
    pr = 515912;
    rev = "3cbc8c646fc63153ff5131c8c0055bd195318a34";
    narHash = "sha256-hMQcB8Nlovu44xs9/hJygM40vEWv1cS/ELPRDhHxDso=";
    attr = "toofan";
    version = "2.2.0";
    author = "gwg313";
    mergeReady = false;
  };
  toolblex = {
    pr = 462355;
    rev = "0e75b4ca914fe196624488be4f55c59ff58cfb39";
    narHash = "sha256-lLhQXBEPQ5rP//RxMYB6Gk6+yTrDdQXKHIwEYwMN7pE=";
    attr = "toolblex";
    version = "0.16";
    author = "fgaz";
    mergeReady = false;
  };
  toppra = {
    pr = 518648;
    rev = "02251bac4ca7a1c270eb017db377fc866b4d4011";
    narHash = "sha256-bjwkKacjaGbS1SF+uWNg+8MWCFStx6iQHzTCMcXEtjI=";
    attr = "toppra";
    version = "0.6.8";
    author = "nim65s";
    mergeReady = false;
  };
  trafficserver10 = {
    pr = 474177;
    rev = "3fa75fc5d84eb4c1cee070c6bd5bb9653d4699af";
    narHash = "sha256-+sf7GxtvfLs8jM4n5Or6XvX7/N67sPcpWa1Dm9JFUvE=";
    attr = "trafficserver10";
    version = "10.1.0";
    author = "randomizedcoder";
    mergeReady = false;
  };
  triangle = {
    pr = 499569;
    rev = "0038237acbca70aabbda385d89cff96b1c55ac40";
    narHash = "sha256-ZLPZEindKT4KMk9YaK/YgzwHqLhqAStK06eaOWGCDDY=";
    attr = "triangle";
    version = "1.6 and octavePackages.femoctave: init at 2.1.8";
    author = "WiredMic";
    mergeReady = false;
  };
  tux-manager = {
    pr = 510611;
    rev = "17849a5723bb5fec5fc1cf7d290cf5dc92f4936f";
    narHash = "sha256-OLkG8ZmSEK9RqOMWOUnmE8fshiH1xBUOloje2OIV0Qo=";
    attr = "tux-manager";
    version = "1.0.4";
    author = "phyrophone";
    mergeReady = false;
  };
  unclack = {
    pr = 515659;
    rev = "259b368cb613ca68afb32286cb7e7606ead09e99";
    narHash = "sha256-CWyPxSB9rx4HFeUxmBqulwlyYHX1dlDvS38E7PhS/TA=";
    attr = "unclack";
    version = "1.3.0";
    author = "yamashitax";
    mergeReady = false;
  };
  unlzw3 = {
    pr = 440120;
    rev = "21ddee55481536021befcd7cf0566179600b13c3";
    narHash = "sha256-+ry+0hdOA/y950igpg3NaqHcnaY8XgXGPQ6lr+AqqAk=";
    attr = "unlzw3";
    version = "";
    author = "Gurjaka";
    mergeReady = false;
  };
  unxip = {
    pr = 509238;
    rev = "2335c17989c7f4477948b04d92f738f287a9d9c0";
    narHash = "sha256-PAlob60z7ONGBrTU9Kne1OwbYJE9IDG6jBQg92ahQzE=";
    attr = "unxip";
    version = "3.0";
    author = "DimitarNestorov";
    mergeReady = false;
  };
  updxy = {
    pr = 521609;
    rev = "23fbe2851582a270094c830e4f93998c93d110c5";
    narHash = "sha256-IhhtQmDqFaN00Af5zwND4lH5iH/ve6gRJCwocn+q5yA=";
    attr = "updxy";
    version = "1.0-25.2";
    author = "bachp";
    mergeReady = false;
  };
  vigil = {
    pr = 506654;
    rev = "48a017c9d5887a35399bf559948b6c184e5e5f06";
    narHash = "sha256-Qdz3K8IiTjhsqzJQ3REI7vRTGEF1PPQiK6aeLCABbiM=";
    attr = "vigil";
    version = "0-unstable-2026-01-04";
    author = "Daru-san";
    mergeReady = false;
  };
  vite-plus = {
    pr = 500492;
    rev = "1af3f381ec5456974338bc996e5b8714e1fab608";
    narHash = "sha256-lvRI2rZFmHexsAK/tE2HMOZ2yy1tCQr9ByILZtCne1o=";
    attr = "vite-plus";
    version = "0.1.18";
    author = "qweered";
    mergeReady = false;
  };
  vkpeak = {
    pr = 513712;
    rev = "2c12dab2ac8011ace5dfadea36a6a299b6ebf9e8";
    narHash = "sha256-db5RFg3LP6ICdFm0+c3HslQVDS6RGfYvKrioKVHSUx4=";
    attr = "vkpeak";
    version = "0-unstable-2026-01-12";
    author = "moeleak";
    mergeReady = false;
  };
  vmnet-helper = {
    pr = 495633;
    rev = "39bedb33d0c4f6221d2ec56eb47607057ae57b85";
    narHash = "sha256-UKqNgHMxpZlNcDSVkDxZc5Mkf/BBW/cJnjRjeE5RGNM=";
    attr = "vmnet-helper";
    version = "v0.9.0";
    author = "quinneden";
    mergeReady = false;
  };
  wacli = {
    pr = 496066;
    rev = "10b83564a225e7e409fe5aa3809cd1f96caafb48";
    narHash = "sha256-53iPlw2Jfuq6DQo/8GN/LQxVT+PXmGLvEOgiKsQHPDE=";
    attr = "wacli";
    version = "0.6.0";
    author = "macalinao";
    mergeReady = false;
  };
  warc3-wet = {
    pr = 440120;
    rev = "21ddee55481536021befcd7cf0566179600b13c3";
    narHash = "sha256-+ry+0hdOA/y950igpg3NaqHcnaY8XgXGPQ6lr+AqqAk=";
    attr = "warc3-wet";
    version = "";
    author = "Gurjaka";
    mergeReady = false;
  };
  warc3-wet-clueweb = {
    pr = 440120;
    rev = "21ddee55481536021befcd7cf0566179600b13c3";
    narHash = "sha256-+ry+0hdOA/y950igpg3NaqHcnaY8XgXGPQ6lr+AqqAk=";
    attr = "warc3-wet-clueweb";
    version = "";
    author = "Gurjaka";
    mergeReady = false;
  };
  wasm-bindgen-cli_0_2_120 = {
    pr = 514867;
    rev = "0761ce720a833fa0a547370019e5c92a459e83db";
    narHash = "sha256-YnHOIQnEdUyp3yIUGmvYodJstlyjS/ghX98Vg1/gM2M=";
    attr = "wasm-bindgen-cli_0_2_120";
    version = "0.2.120";
    author = "Javier-varez";
    mergeReady = false;
  };
  within = {
    pr = 450469;
    rev = "0e98534067602089b54e8f4f67a68f9d2b46596a";
    narHash = "sha256-M8kxTXsqN0B7tC2Ir+3hCjZSYzvci8Pp76BH6ntDBug=";
    attr = "within";
    version = "1.1.4";
    author = "examosa";
    mergeReady = false;
  };
  wl-proxy = {
    pr = 520318;
    rev = "13e5666057cb8b72841d8e9fb0beb21c68c9c287";
    narHash = "sha256-cxPWUwuZdl+eia+R7RZ2sdqFeQEshuyprjvBTmfWcY0=";
    attr = "wl-proxy";
    version = "0.1.2";
    author = "HigherOrderLogic";
    mergeReady = false;
  };
  wlctl = {
    pr = 506913;
    rev = "44fa3d50ab375fd8f5070f61c544d4252475b579";
    narHash = "sha256-ZfqholjdHyl0zoiX28h/q0Buh5fmZLTjo79CcHUS2BU=";
    attr = "wlctl";
    version = "0.1.5";
    author = "preArcMed821";
    mergeReady = false;
  };
  wren = {
    pr = 476592;
    rev = "1fba54b5d2046a3904f5fcd865823e000e5d2129";
    narHash = "sha256-U7nyzA4XMUW/t2ew01Nwompe7aPRghJAwDWaNGi6Kh0=";
    attr = "wren";
    version = "0.4.0";
    author = "Zaczero";
    mergeReady = false;
  };
  wren-cli = {
    pr = 476592;
    rev = "1fba54b5d2046a3904f5fcd865823e000e5d2129";
    narHash = "sha256-U7nyzA4XMUW/t2ew01Nwompe7aPRghJAwDWaNGi6Kh0=";
    attr = "wren-cli";
    version = "0.4.0";
    author = "Zaczero";
    mergeReady = false;
  };
  xendmail = {
    pr = 507982;
    rev = "0f660992c738db8251a6bebbd17cfcb358c28627";
    narHash = "sha256-Ad6MtclYHQ0BtresLnIoNJ77eneXEqAbDxsGFVZBeaI=";
    attr = "xendmail";
    version = "0.5.0";
    author = "philocalyst";
    mergeReady = false;
  };
  xonotic = {
    pr = 521771;
    rev = "00ce5003f5c84360c8a3cdb4449ff77bdf3513ec";
    narHash = "sha256-Q04h+1MCFGRl7OmkHijG7WlksXapuxMf2StLonFofwo=";
    attr = "xonotic";
    version = "";
    author = "philocalyst";
    mergeReady = false;
  };
  xr-chaperone = {
    pr = 513111;
    rev = "0b75368972da37e9ce21b1c549fa56a39e43571c";
    narHash = "sha256-xlVnAh69mnk65qlG5OlqhFq/H95JTQOa2R17WIwzuRY=";
    attr = "xr-chaperone";
    version = "0-unstable-2026-03-16";
    author = "ToasterUwU";
    mergeReady = false;
  };
  yubal = {
    pr = 518335;
    rev = "34f8ced5b3aa057d4415d11892691cf8e7fdcda8";
    narHash = "sha256-ZzAW3lbMkp7wljwmeLO/9DkdyRYuQaqVFN5C6SdS8yI=";
    attr = "yubal";
    version = "0.7.2";
    author = "Skullman-G";
    mergeReady = false;
  };
  zen-browser = {
    pr = 496647;
    rev = "4864b72919f6baa43781e44cd92b009a349b2f37";
    narHash = "sha256-YsPNeYBbqkjWmYSXpAgjO7zY+TYE6VmZyI4v8kYCs/U=";
    attr = "zen-browser";
    version = "1.19.5b";
    author = "Hythera";
    mergeReady = false;
  };
  zlib-state = {
    pr = 440120;
    rev = "21ddee55481536021befcd7cf0566179600b13c3";
    narHash = "sha256-+ry+0hdOA/y950igpg3NaqHcnaY8XgXGPQ6lr+AqqAk=";
    attr = "zlib-state";
    version = "";
    author = "Gurjaka";
    mergeReady = false;
  };
  zmk-cli = {
    pr = 501939;
    rev = "40420e84e84ff53d4a2052153c66beb45cad4c1a";
    narHash = "sha256-DP5LuNqNBpEgu2UNaOUYRS2rjsZgQ8V7247U5iD2/LE=";
    attr = "zmk-cli";
    version = "0.4.1";
    author = "JarvisCraft";
    mergeReady = false;
  };
  zombies = {
    pr = 521835;
    rev = "3000c743d58c11b90c16ffe2f23805d9708e8b5c";
    narHash = "sha256-PDlg3uWmHtqmdioh3Ecao93mmKBdNJ0krzvLU6Zmi/Q=";
    attr = "zombies";
    version = "0-unstable-2006-03-07";
    author = "castorNova2";
    mergeReady = false;
  };
  zotero-mcp-server = {
    pr = 501295;
    rev = "31b5cebf2fc5a5da4ec49dbbac44da47af8f9895";
    narHash = "sha256-L8ph629T9t4UuZKg4+bE5zRORNQJjukPTxJ9FJSIrXU=";
    attr = "zotero-mcp-server";
    version = "0.2.2";
    author = "yzx9";
    mergeReady = false;
  };
}
