"""Export the local index to a Nix attrset consumed by flake.nix.

Each entry carries the head commit SHA and SRI narHash, so the flake can
fetch the tarball purely (no --impure required). Rows missing a narHash are
skipped by default - run `prpkgs prefetch` to fill them in.

When multiple PRs propose the same leaf name we pick:
    1. has narHash over not
    2. merge-ready over not
    3. non-draft over draft
    4. most-recently updated
"""

from __future__ import annotations

import re
from datetime import datetime
from io import StringIO
from typing import Iterable

from .db import Database
from .models import PendingPackage

NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_-]*$")


def _better(candidate: PendingPackage, current: PendingPackage) -> bool:
    if bool(candidate.nar_hash) != bool(current.nar_hash):
        return bool(candidate.nar_hash)
    if candidate.merge_ready != current.merge_ready:
        return candidate.merge_ready
    if candidate.draft != current.draft:
        return not candidate.draft
    return (candidate.pr_updated_at or "") > (current.pr_updated_at or "")


def pick_best(
    packages: Iterable[PendingPackage], require_hash: bool
) -> tuple[dict[str, PendingPackage], int]:
    best: dict[str, PendingPackage] = {}
    skipped_no_hash = 0
    for pkg in packages:
        attr = pkg.attr_path or pkg.name
        if not attr or "." in attr:
            continue
        if not NAME_RE.match(attr):
            continue
        if require_hash and not pkg.nar_hash:
            skipped_no_hash += 1
            continue
        existing = best.get(attr)
        if existing is None or _better(pkg, existing):
            best[attr] = pkg
    return best, skipped_no_hash


def _escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render_pending_nix(
    packages: Iterable[PendingPackage], require_hash: bool = True
) -> tuple[str, dict]:
    best, skipped_no_hash = pick_best(packages, require_hash=require_hash)
    buf = StringIO()
    buf.write(
        "# Generated by `prpkgs export` on "
        + datetime.now().isoformat(timespec="seconds")
        + ". Do not edit by hand.\n"
    )
    buf.write(
        "# Maps a leaf package name to the open nixpkgs PR snapshot that\n"
        "# introduces it. Consumed by flake.nix.\n"
    )
    buf.write("{\n")
    for name in sorted(best):
        pkg = best[name]
        attr = pkg.attr_path or pkg.name
        version = pkg.version or ""
        if pkg.nar_hash and pkg.head_rev:
            buf.write(
                f"  {name} = {{\n"
                f"    pr = {pkg.pr_number};\n"
                f'    rev = "{_escape(pkg.head_rev)}";\n'
                f'    narHash = "{_escape(pkg.nar_hash)}";\n'
                f'    attr = "{_escape(attr)}";\n'
                f'    version = "{_escape(version)}";\n'
                f'    author = "{_escape(pkg.author)}";\n'
                f"    mergeReady = {'true' if pkg.merge_ready else 'false'};\n"
                f"  }};\n"
            )
        else:
            # impure fallback, only emitted with --allow-unhashed
            buf.write(
                f"  {name} = {{\n"
                f"    pr = {pkg.pr_number};\n"
                f'    attr = "{_escape(attr)}";\n'
                f'    version = "{_escape(version)}";\n'
                f'    author = "{_escape(pkg.author)}";\n'
                f"    mergeReady = {'true' if pkg.merge_ready else 'false'};\n"
                f"    impure = true;\n"
                f"  }};\n"
            )
    buf.write("}\n")
    return buf.getvalue(), {"kept": len(best), "skipped_no_hash": skipped_no_hash}


def export(db: Database, require_hash: bool = True) -> tuple[str, dict]:
    rows = db.list_recent(limit=100000, include_drafts=False)
    return render_pending_nix(rows, require_hash=require_hash)
